#import "@preview/codelst:2.0.2": sourcefile, sourcecode

= Geometry

#include "Point.typ"
#include "area.typ"
#include "ccw.typ"
#include "projection.typ"
#include "isinPolygon.typ"
#include "convex_hull.typ"
#include "isconvex.typ"
#include "closest_pair.typ"
#include "lineDistance.typ"
#include "onSegment.typ"
#include "circumcircle.typ"
#include "commonTangents.typ"
#include "segDistance.typ"
#include "segInter.typ"
#include "ssDist.typ"
#include "diamConvex.typ"
#include "lineInter.typ"
#include "Polygon_cut.typ"
#include "trincircle.typ"
#include "clInter.typ"
#include "ccInter.typ"
#include "minEncloseCirc.typ"